#!/usr/bin/env bash
#
# build-capability-index.sh
#
# Parses all agent frontmatter and produces a machine-readable capability index.
# This is the authoritative routing substrate — the orchestrator reads this
# generated file rather than grepping 76 agent files at runtime.
#
# Run after any change to agent frontmatter:
#   ./enterprise-team/scripts/build-capability-index.sh
#
# Then commit the updated capability-index.yaml.
#
# CI should run this and fail if the checked-in index differs from the freshly
# generated one — that prevents silent drift between agent frontmatter and the
# routing substrate.

set -euo pipefail

PLUGIN_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
AGENTS_DIR="${PLUGIN_ROOT}/agents"
ALIASES_FILE="${PLUGIN_ROOT}/capability-aliases.yaml"
INDEX_FILE="${PLUGIN_ROOT}/capability-index.yaml"

if [ ! -d "$AGENTS_DIR" ]; then
  echo "ERROR: agents directory not found at $AGENTS_DIR" >&2
  exit 1
fi

if [ ! -f "$ALIASES_FILE" ]; then
  echo "ERROR: capability-aliases.yaml not found at $ALIASES_FILE" >&2
  exit 1
fi

# Extract controlled domain list from capability-aliases.yaml
CONTROLLED_DOMAINS=$(awk '
  /^domains:/ { in_domains = 1; next }
  /^[a-z]/ && !/^  / { in_domains = 0 }
  in_domains && /^  - / {
    sub(/^  - /, "")
    sub(/[ ]*#.*$/, "")
    gsub(/[ ]+$/, "")
    if (length($0) > 0) print $0
  }
' "$ALIASES_FILE")

if [ -z "$CONTROLLED_DOMAINS" ]; then
  echo "ERROR: could not extract controlled domains from $ALIASES_FILE" >&2
  exit 1
fi

# Start writing the index
{
  echo "# capability-index.yaml"
  echo "#"
  echo "# AUTO-GENERATED by scripts/build-capability-index.sh. Do not edit by hand."
  echo "# Source of truth: the 'capabilities:' frontmatter in each agents/*.md."
  echo "# Regenerate after any agent frontmatter change and commit the result."
  echo "#"
  echo "# This file is the machine-readable routing substrate the enterprise-orchestrator"
  echo "# consults when matching tasks to specialists. It inverts the agent -> capabilities"
  echo "# relationship into a capability-domain -> agents lookup."
  echo ""
  echo "generated_at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo "agent_count: $(ls "$AGENTS_DIR"/*.md 2>/dev/null | wc -l | tr -d ' ')"
  echo ""
  echo "# ===== DOMAIN -> AGENTS INDEX ====="
  echo "# For each controlled domain, list the agents that declare it and the qualifiers they carry."
  echo "by_domain:"
} > "$INDEX_FILE"

# Build the domain -> agents map
while IFS= read -r domain; do
  [ -z "$domain" ] && continue

  # Temporary collection of matching agents for this domain
  TMPFILE=$(mktemp)
  : > "$TMPFILE"

  for agent_file in "$AGENTS_DIR"/*.md; do
    [ -f "$agent_file" ] || continue
    agent_name=$(basename "$agent_file" .md)

    # Extract the capabilities block from YAML frontmatter.
    # Frontmatter is bounded by --- lines. We parse only the first block.
    capabilities_block=$(awk '
      /^---$/ { count++; if (count == 2) exit; next }
      count == 1 { print }
    ' "$agent_file" | awk '
      /^capabilities:/ { in_caps = 1; next }
      /^[a-z]/ && !/^  / { in_caps = 0 }
      in_caps && /^  - / { print }
    ')

    [ -z "$capabilities_block" ] && continue

    # Each line is either:
    #   - domain: [q1, q2]
    #   - domain
    # Strip leading "  - ", then parse domain and optional qualifier list.
    while IFS= read -r line; do
      [ -z "$line" ] && continue
      stripped=$(echo "$line" | sed 's/^  - //')
      line_domain=$(echo "$stripped" | awk -F: '{ print $1 }' | sed 's/[[:space:]]*$//')

      if [ "$line_domain" = "$domain" ]; then
        # Extract qualifiers if present
        if echo "$stripped" | grep -q ':'; then
          qualifiers=$(echo "$stripped" | awk -F: '{ print $2 }' | sed 's/^[[:space:]]*\[//; s/\][[:space:]]*$//; s/[[:space:]]*,[[:space:]]*/, /g; s/^[[:space:]]*//; s/[[:space:]]*$//')
          if [ -n "$qualifiers" ]; then
            echo "    - agent: $agent_name" >> "$TMPFILE"
            echo "      qualifiers: [$qualifiers]" >> "$TMPFILE"
          else
            echo "    - agent: $agent_name" >> "$TMPFILE"
            echo "      qualifiers: []" >> "$TMPFILE"
          fi
        else
          echo "    - agent: $agent_name" >> "$TMPFILE"
          echo "      qualifiers: []" >> "$TMPFILE"
        fi
      fi
    done <<< "$capabilities_block"
  done

  # Only write the domain entry if at least one agent declared it
  if [ -s "$TMPFILE" ]; then
    echo "  ${domain}:" >> "$INDEX_FILE"
    cat "$TMPFILE" >> "$INDEX_FILE"
  fi

  rm -f "$TMPFILE"
done <<< "$CONTROLLED_DOMAINS"

# Also emit an inverse index (agent -> capabilities) for debugging / auditing
{
  echo ""
  echo "# ===== AGENT -> CAPABILITIES INDEX ====="
  echo "# Inverse view for auditing. Listed in alphabetical order."
  echo "by_agent:"
} >> "$INDEX_FILE"

for agent_file in "$AGENTS_DIR"/*.md; do
  [ -f "$agent_file" ] || continue
  agent_name=$(basename "$agent_file" .md)

  capabilities_block=$(awk '
    /^---$/ { count++; if (count == 2) exit; next }
    count == 1 { print }
  ' "$agent_file" | awk '
    /^capabilities:/ { in_caps = 1; next }
    /^[a-z]/ && !/^  / { in_caps = 0 }
    in_caps && /^  - / { print }
  ')

  if [ -n "$capabilities_block" ]; then
    echo "  ${agent_name}:" >> "$INDEX_FILE"
    while IFS= read -r line; do
      [ -z "$line" ] && continue
      echo "  $line" >> "$INDEX_FILE"
    done <<< "$capabilities_block"
  fi
done

# Report coverage — only count domains in the by_domain section, not by_agent entries
DOMAINS_COVERED=$(awk '
  /^# ===== AGENT/ { exit }
  /^  [a-z][a-z-]*:$/ { gsub(":", ""); gsub("^  ", ""); print }
' "$INDEX_FILE" | sort -u | wc -l | tr -d ' ')
TOTAL_DOMAINS=$(echo "$CONTROLLED_DOMAINS" | wc -l | tr -d ' ')

echo "Generated: $INDEX_FILE" >&2
echo "Controlled domains: $TOTAL_DOMAINS" >&2
echo "Domains with at least one agent: $DOMAINS_COVERED" >&2
echo "Agents indexed: $(ls "$AGENTS_DIR"/*.md 2>/dev/null | wc -l | tr -d ' ')" >&2

# Warn if a controlled domain has zero agents — this is almost always a bug
if [ "$DOMAINS_COVERED" -lt "$TOTAL_DOMAINS" ]; then
  MISSING_DOMAINS=$(comm -23 \
    <(echo "$CONTROLLED_DOMAINS" | sort -u) \
    <(awk '
        /^# ===== AGENT/ { exit }
        /^  [a-z][a-z-]*:$/ { gsub(":", ""); gsub("^  ", ""); print }
      ' "$INDEX_FILE" | sort -u))
  echo "" >&2
  echo "WARNING: the following controlled domains have no agents declaring them:" >&2
  echo "$MISSING_DOMAINS" | sed 's/^/  - /' >&2
fi
